export const projectsData = [
  {
    id: "toycity", 
    title: "ToyCity",
    category: "E-commerce",
    shortDescription: "Uma experiência de compra imersiva para loja de brinquedos. Design focado em conversão.",
    fullDescription: "A ToyCity é a maior varejista de brinquedos de Luanda. Eles precisavam de uma presença digital que refletisse a alegria da loja física, mas com a eficiência de um e-commerce moderno.",
    imageUrl: "/ToyCity-Poster.jpg",
    gallery: [], 
    tags: ["Next.js 14", "Zustand", "Stripe", "Tailwind", "Framer Motion"],
    metrics: { conversion: "4.5%", skus: "500+" },
    challenge: "O site antigo era lento e difícil de navegar no móvel. O cliente queria algo 'mágico' mas que carregasse instantaneamente.",
    solution: "Criamos uma SPA (Single Page Application) com transições fluidas. O carrinho é persistente e a busca usa Algolia para resultados em <20ms.",
    year: "2025",
    client: "ToyCity Angola",
    role: "Full Stack Dev",
    link: "https://toycity.ao"
  },
  {
    id: "pharmapp",
    title: "Pharmapp",
    category: "SaaS / Fintech",
    shortDescription: "Ecossistema de gestão farmacêutica certificado pela AGT. Controle total de stock e lotes.",
    fullDescription: "Sistema desktop e web para gestão de farmácias em Angola, focado em conformidade fiscal e rapidez no atendimento.",
    imageUrl: "/PharmApp-P1.jpg",
    gallery: ["/PharmApp-P2.jpg"],
    tags: ["TypeScript", "Electron", "PostgreSQL", "SAFT-AO"],
    metrics: { users: "50+", uptime: "99.9%" },
    challenge: "Integrar comunicação com a AGT em tempo real e funcionar offline quando a internet cai.",
    solution: "Arquitetura 'Local-First' usando Electron e SQLite, sincronizando com a nuvem quando há conexão.",
    year: "2024",
    client: "Softwise Internal",
    role: "Lead Engineer",
    link: "#"
  },
  {
    id: "instantpay",
    title: "InstantPay",
    category: "Infraestrutura",
    shortDescription: "Gateway de pagamentos robusto com arquitetura de micro-serviços.",
    fullDescription: "Infraestrutura de pagamentos para processar transações multicanal (Multicaixa, Mobile Money) com alta disponibilidade.",
    imageUrl: "/instant.jpg",
    gallery: ["/instant-arch.jpg", "/instant-code.jpg"],
    tags: ["Go", "Kubernetes", "Redis", "gRPC"],
    metrics: { tps: "1000+", latency: "50ms" },
    challenge: "Garantir consistência transacional (ACID) em um ambiente distribuído.",
    solution: "Implementação do padrão Saga para transações distribuídas e uso intensivo de Redis para cache.",
    year: "2024",
    client: "Fintech Confidential",
    role: "Backend Architect",
    link: "#"
  },
  {
    id: "akira-manzambi",
    title: "Akira Manzambi",
    category: "Portfolio / CMS",
    shortDescription: "Plataforma de portfólio totalmente gerível com dashboard customizável e arquitetura cloud.",
    fullDescription: "Um sistema de portfólio robusto desenhado para o Art Director Akira Manzambi. O diferencial técnico é a dashboard 'No-Code' que permite ao designer alterar não só os projetos, mas a estrutura do rodapé, cores e tipografia em tempo real.",
    imageUrl: "/akira.png", 
    gallery: ["/akira2.png", "/akira3.png"],
    tags: ["Next.js", "Sanity CMS", "Cloudinary", "Framer Motion"],
    metrics: { performance: "100/100", uptime: "99.9%" },
    challenge: "O cliente precisava de liberdade total para alterar a identidade visual do site sem depender de desenvolvedores a cada mudança.",
    solution: "Criamos um CMS headless integrado onde cada componente do frontend escuta alterações de configuração. O site adapta o layout baseado nas preferências definidas no painel.",
    year: "2025",
    client: "Studio Akira Manzambi",
    role: "Full Stack Development",
    link: "https://akiramanzambi7.com"
  },
];